---
- name: Verify
  hosts: all
  tasks:
    - name: Windows | Terragrunt should be functionnal
      ansible.windows.win_command: terragrunt --version
      register: terragrunt_result
      changed_when: false

    - name: Windows | Verify commands outputs
      ansible.builtin.assert:
        that:
          - terragrunt_result.rc == 0
        success_msg: "All tests passed"
